if(!localStorage.getItem('willyol-visite')){localStorage.setItem('willyol-visite','1');}
document.addEventListener('DOMContentLoaded',()=>{const heroVideo=document.querySelector('.hero-video');if(heroVideo){heroVideo.addEventListener('error',()=>{heroVideo.style.display='none';const hero=document.querySelector('.hero');if(hero)hero.style.background='var(--noir)';});const playPromise=heroVideo.play();if(playPromise!==undefined){playPromise.catch(()=>{console.info('[WillyOL] Autoplay vidéo Hero bloqué par le navigateur.');});}}
const showreelCard=document.querySelector('.showreel-card');const showreelVideo=document.getElementById('showreel-video');if(showreelCard&&showreelVideo){const ouvrirPleinEcran=()=>{const req=showreelVideo.requestFullscreen||showreelVideo.webkitRequestFullscreen||showreelVideo.mozRequestFullScreen||showreelVideo.msRequestFullscreen;if(req)req.call(showreelVideo);};showreelCard.addEventListener('click',ouvrirPleinEcran);showreelCard.addEventListener('keydown',(e)=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();ouvrirPleinEcran();}});const onFullscreenChange=()=>{const isFullscreen=document.fullscreenElement===showreelVideo||document.webkitFullscreenElement===showreelVideo||document.mozFullScreenElement===showreelVideo||document.msFullscreenElement===showreelVideo;if(isFullscreen){showreelVideo.setAttribute('controls','');showreelVideo.muted=false;showreelVideo.play().catch(()=>{});}else{showreelVideo.removeAttribute('controls');showreelVideo.muted=true;}};document.addEventListener('fullscreenchange',onFullscreenChange);document.addEventListener('webkitfullscreenchange',onFullscreenChange);document.addEventListener('mozfullscreenchange',onFullscreenChange);document.addEventListener('MSFullscreenChange',onFullscreenChange);}
(function initSelectedWork(){const SLUGS_VITRINE=['izidoor','pschhh','eurockeenes'];const wrap=document.querySelector('.selected-wrap');const panel=document.querySelector('.selected-panel');const split=document.querySelector('.selected-split');const navEl=document.querySelector('.selected-nav');const track=document.querySelector('.selected-nav-track');const main=document.querySelector('.selected-main');if(!wrap||!panel||!split||!navEl||!track||!main)return;if(typeof PROJETS==='undefined'||!Array.isArray(PROJETS)){console.warn('[WillyOL] PROJETS manquant — Selected Work non rendu.');return;}
const norm=(s)=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');const mapProjets=new Map(PROJETS.map(p=>[norm(p.nom),p]));const projetsVitrine=SLUGS_VITRINE.map(slug=>mapProjets.get(norm(slug))).filter(Boolean);if(projetsVitrine.length===0){console.warn('[WillyOL] Aucun projet de vitrine trouvé.');return;}
function rewritePath(path){if(!path)return path;return path.replace(/^\.\.\//,'');}
const mainTrack=document.createElement('div');mainTrack.className='selected-main-track';main.appendChild(mainTrack);projetsVitrine.forEach((p,i)=>{const num=String(i+1).padStart(2,'0');const navItem=document.createElement('a');navItem.className='selected-nav-item'+(i===0?' actif':'');navItem.href=p.href||'#';navItem.dataset.idx=i;navItem.setAttribute('data-curseur','');navItem.innerHTML=`
        <span class="selected-nav-titre">${p.nom}</span>
        <span class="selected-nav-num">${num}</span>
      `;track.appendChild(navItem);const cover=rewritePath(p.cover);let mediaHtml;if(cover){if(p.video){mediaHtml=`<video autoplay muted loop playsinline preload="metadata"><source src="${cover}"></video>`;}else{mediaHtml=`<img src="${cover}" alt="${p.nom}" loading="lazy">`;}}else{mediaHtml=`<div style="width:100%;height:100%;background:rgba(255,255,255,0.05)"></div>`;}
const media=document.createElement('div');media.className='selected-media';media.dataset.idx=i;const viewLabel=(window.langueActuelle==='fr')?`Voir ${p.nom}`:`View ${p.nom}`;media.innerHTML=`
        <a href="${p.href}" data-curseur aria-label="${viewLabel}">
          ${mediaHtml}
          <div class="selected-media-meta">
            <span class="selected-media-titre">${p.nom}</span>
            <span class="selected-media-cat">${p.meta || ''}</span>
          </div>
        </a>
      `;mainTrack.appendChild(media);});const N=projetsVitrine.length;const SEUIL_EXPAND_FIN=0.32;const SEUIL_SCROLL_DEB=0.40;const SEUIL_SCROLL_FIN=0.92;let navItemEls=Array.from(track.querySelectorAll('.selected-nav-item'));let mediaEls=Array.from(mainTrack.querySelectorAll('.selected-media'));let rafId=null;let dernierIdxActif=0;function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function majProgression(){rafId=null;const rect=wrap.getBoundingClientRect();const total=wrap.offsetHeight-window.innerHeight;if(total<=0)return;const scrolled=-rect.top;const p=clamp(scrolled/total,0,1);const pExpand=clamp(p/SEUIL_EXPAND_FIN,0,1);const eased=pExpand<0.5?4*pExpand*pExpand*pExpand:1-Math.pow(-2*pExpand+2,3)/2;panel.style.setProperty('--p-expand',eased.toFixed(4));wrap.classList.toggle('panel-plein',eased>0.9);wrap.classList.toggle('panel-idle',eased<0.03);let pScroll=0;if(p>SEUIL_SCROLL_DEB){pScroll=clamp((p-SEUIL_SCROLL_DEB)/(SEUIL_SCROLL_FIN-SEUIL_SCROLL_DEB),0,1);}
const idxContinu=pScroll*(N-1);const idxEntier=Math.round(idxContinu);if(mediaEls.length>1){const rect0=mediaEls[0].getBoundingClientRect();const rect1=mediaEls[1].getBoundingClientRect();const step=rect1.top-rect0.top;const mainRect=main.getBoundingClientRect();const mediaH=rect0.height;const padTop=Math.max(0,(mainRect.height-mediaH)/2);mainTrack.style.setProperty('--main-pad-top',padTop+'px');const mainShift=idxContinu*step;mainTrack.style.setProperty('--main-shift',mainShift+'px');track.style.setProperty('--nav-shift','0px');}else if(mediaEls.length===1){const rect0=mediaEls[0].getBoundingClientRect();const mainRect=main.getBoundingClientRect();const padTop=Math.max(0,(mainRect.height-rect0.height)/2);mainTrack.style.setProperty('--main-pad-top',padTop+'px');}
if(idxEntier!==dernierIdxActif){navItemEls.forEach((el,i)=>{el.classList.toggle('actif',i===idxEntier);});dernierIdxActif=idxEntier;}}
function onScroll(){if(rafId!==null)return;rafId=requestAnimationFrame(majProgression);}
window.addEventListener('scroll',onScroll,{passive:true});window.addEventListener('resize',onScroll);majProgression();if(document.readyState==='complete'){requestAnimationFrame(majProgression);}else{window.addEventListener('load',()=>{requestAnimationFrame(majProgression);});}
if('IntersectionObserver'in window){const obsVid=new IntersectionObserver((entries)=>{entries.forEach(entry=>{const vid=entry.target.querySelector('video');if(!vid)return;if(entry.isIntersecting){vid.play().catch(()=>{});}else{vid.pause();}});},{threshold:0.1});mediaEls.forEach(m=>obsVid.observe(m));}})();});(function initXsTransition(){const wrap=document.querySelector('.xs-wrap');const stage=document.querySelector('.xs-stage');if(!wrap||!stage)return;let inView=false;let rafId=null;function maj(){rafId=null;const rect=wrap.getBoundingClientRect();const zone=wrap.offsetHeight-window.innerHeight;if(zone<=0)return;const scrolled=-rect.top;const t=Math.max(0,Math.min(1,scrolled/zone));stage.style.setProperty('--t',t.toFixed(4));}
function onScroll(){if(!inView||rafId!==null)return;rafId=requestAnimationFrame(maj);}
const io=new IntersectionObserver((entries)=>{inView=entries[0].isIntersecting;if(inView)maj();},{threshold:0});io.observe(wrap);window.addEventListener('scroll',onScroll,{passive:true});window.addEventListener('resize',maj);maj();})();document.addEventListener('DOMContentLoaded',()=>{const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const lerp=(a,b,t)=>a+(b-a)*t;const set=(el,k,v)=>el?.style.setProperty(k,v);const easeOut3=t=>1-Math.pow(1-clamp(t,0,1),3);const easeIO3=t=>{t=clamp(t,0,1);return t<0.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;};function scrollP(el,s=0.95,e=0.1){const r=el.getBoundingClientRect(),vh=window.innerHeight;return clamp((vh*s-r.top)/(vh*(s-e)),0,1);}
function centerOffset(el){const r=el.getBoundingClientRect();return(r.top+r.height*0.5)-window.innerHeight*0.5;}
const fns=[];let raf=null;const tick=()=>{raf=null;fns.forEach(f=>f());};const pump=()=>{if(!raf)raf=requestAnimationFrame(tick);};window.addEventListener('scroll',pump,{passive:true});window.addEventListener('resize',pump);window.addEventListener('load',()=>requestAnimationFrame(tick));const hero=document.querySelector('.hero');const heroScene=document.querySelector('.hero-scene');const heroVidWrap=document.querySelector('.hero-video-wrap');const heroKm27=hero?hero.querySelector('.hero-km27'):null;if(hero&&heroScene&&!window.__vitrineD){const bandG=document.createElement('div');const bandD=document.createElement('div');bandG.className='hero-band-blanc hero-band-blanc--g';bandD.className='hero-band-blanc hero-band-blanc--d';hero.appendChild(bandG);hero.appendChild(bandD);let cloneG=null,cloneD=null;if(heroKm27){cloneG=heroKm27.cloneNode(true);cloneD=heroKm27.cloneNode(true);[cloneG,cloneD].forEach(cl=>{cl.classList.add('hero-km27--noir');cl.querySelectorAll('.hero-km27-text').forEach(el=>{el.style.animation='none';el.style.opacity='1';el.style.transform='none';});document.body.appendChild(cl);});}
fns.push(()=>{const rect=heroScene.getBoundingClientRect();const zone=heroScene.offsetHeight-window.innerHeight;if(zone<=0)return;const p=clamp(-rect.top/zone,0,1);const heroW=hero.offsetWidth;const heroH=hero.offsetHeight;const hRect=hero.getBoundingClientRect();const vRect=heroVidWrap?heroVidWrap.getBoundingClientRect():null;const vidLeft=vRect?vRect.left-hRect.left:heroW*0.09;const vidTop=vRect?vRect.top-hRect.top:heroH*0.15;const vidW=vRect?vRect.width:heroW*0.82;const vidH=vRect?vRect.height:vidW*9/16;const vidBottom=heroH-vidTop-vidH;const vidRight=heroW-vidLeft-vidW;const vidBR=vRect?parseFloat(getComputedStyle(heroVidWrap).borderRadius)||24:24;const vidCX=vidLeft+vidW*0.5;const vidCY=vidTop+vidH*0.5;const heroP=clamp(p/0.70,0,1);const heroPE=(heroP*heroP*heroP*heroP*heroP).toFixed(4);hero.style.setProperty('--hero-p',heroPE);if(cloneG)cloneG.style.setProperty('--hero-p',heroPE);if(cloneD)cloneD.style.setProperty('--hero-p',heroPE);const pAlin=clamp(p/0.70,0,1);const pA=pAlin*pAlin*pAlin*pAlin*pAlin;const wG=pA*vidLeft;const wD=pA*vidRight;bandG.style.width=wG.toFixed(1)+'px';bandD.style.width=wD.toFixed(1)+'px';const aT=pA*vidTop;const aR=pA*vidRight;const aB=pA*vidBottom;const aL=pA*vidLeft;const pBlin=clamp((p-0.65)/0.35,0,1);const pB=pBlin;const curW=vidW*(1-pB);const curH=curW*9/16;const bL=vidCX-curW*0.5;const bR=heroW-vidCX-curW*0.5;const bT=vidCY-curH*0.5;const bB=heroH-vidCY-curH*0.5;const blendLin=clamp((p-0.65)/0.10,0,1);const blend=blendLin;const useT=aT+(bT-aT)*blend;const useR=aR+(bR-aR)*blend;const useB=aB+(bB-aB)*blend;const useL=aL+(bL-aL)*blend;const radiusActuel=vidBR*pA;if(p>0.001){hero.style.clipPath=`inset(${useT.toFixed(1)}px ${useR.toFixed(1)}px ${useB.toFixed(1)}px ${useL.toFixed(1)}px round ${radiusActuel.toFixed(1)}px)`;}else{hero.style.clipPath='';}
if(cloneG||cloneD){const km27Rect=heroKm27?heroKm27.getBoundingClientRect():hRect;const fixedTop=km27Rect.top;const fixedLeft=hRect.left;const fixedW=heroW;const fixedH=km27Rect.height;[cloneG,cloneD].forEach(cl=>{if(!cl)return;cl.style.top=fixedTop+'px';cl.style.left=fixedLeft+'px';cl.style.width=fixedW+'px';cl.style.height=fixedH+'px';});if(cloneG){cloneG.style.clipPath=wG>0.5?`inset(0px ${(fixedW - wG).toFixed(1)}px 0px 0px)`:'inset(0 100% 0 0)';}
if(cloneD){cloneD.style.clipPath=wD>0.5?`inset(0px 0px 0px ${(fixedW - wD).toFixed(1)}px)`:'inset(0 0 0 100%)';}}});}
if(heroScene&&!window.__vitrineD){const CONTENU_OFFSET_MAX=50;const SEUIL_INTERNE=0.70;const DUREE_PARALLAXE=1.5;fns.push(()=>{const sceneRect=heroScene.getBoundingClientRect();const sceneH=heroScene.offsetHeight;const vh=window.innerHeight;const scrolled=-sceneRect.top;const debut=(sceneH-vh)*SEUIL_INTERNE;const duree=vh*DUREE_PARALLAXE;const tLin=clamp((scrolled-debut)/duree,0,1);const t=tLin*tLin*(3-2*tLin);const offset=CONTENU_OFFSET_MAX*(1-t);document.documentElement.style.setProperty('--contenu-offset',offset.toFixed(2));});}
const ticker=document.querySelector('.ticker');if(ticker){let track2=ticker.querySelector('.ticker-track-2');if(!track2){const track1=ticker.querySelector('.ticker-track');track2=track1.cloneNode(true);track2.className='ticker-track-2';ticker.appendChild(track2);}
const track1=ticker.querySelector('.ticker-track');const W1=track1.scrollWidth/2;const W2=track2.scrollWidth/2;let lastY=window.scrollY;let vel=0;let offset1=0;let offset2=0;fns.push(()=>{const dy=window.scrollY-lastY;lastY=window.scrollY;vel=lerp(vel,dy,0.2);const speed=vel*1.8;offset1-=speed;offset2+=speed*0.6;offset1=((offset1%W1)+W1)%W1;offset2=((offset2%W2)+W2)%W2;set(track1,'--ticker-x1',`-${offset1.toFixed(2)}px`);set(track2,'--ticker-x2',`-${offset2.toFixed(2)}px`);track1.style.transform=`translateX(-${offset1.toFixed(2)}px)`;track2.style.transform=`translateX(-${offset2.toFixed(2)}px)`;});}
document.querySelectorAll('.separateur').forEach(s=>fns.push(()=>set(s,'--p-sep',easeIO3(scrollP(s,0.98,0.5)).toFixed(4))));const secAbout=document.querySelector('.section-about');const abTitre=document.querySelector('.about-titre');const abIdentity=document.querySelector('.about-identity');const abContent=document.querySelector('.about-content');const abMarquee=document.querySelector('.about-marquee');const abStats=document.querySelector('.about-stats');if(secAbout){fns.push(()=>{const off=centerOffset(secAbout);if(abIdentity)abIdentity.style.transform=`translateY(${(off * -0.10).toFixed(2)}px)`;if(abContent)abContent.style.transform=`translateY(${(off * 0.06).toFixed(2)}px)`;if(abMarquee)abMarquee.style.transform=`translateY(${(off * -0.04).toFixed(2)}px)`;if(abStats)abStats.style.transform=`translateY(${(off * 0.08).toFixed(2)}px)`;});}
const expGrille=document.querySelector('.expertise-grille');const expLabel=document.querySelector('.about-expertise .label-section');if(expGrille){fns.push(()=>{const p=scrollP(expGrille,0.9,0.15);set(expLabel,'--p-exp-label',easeIO3(p).toFixed(4));expGrille.querySelectorAll('.expertise-item').forEach((el,i)=>{const ep=easeOut3(clamp((p-i*0.14)*5,0,1));el.style.setProperty('--ep',ep.toFixed(4));el.querySelectorAll('.expertise-num, .expertise-titre').forEach(c=>c.style.setProperty('--ep',ep.toFixed(4)));});});}
const secFeat=document.querySelector('.section-featured');const featCard=document.querySelector('.featured-card');const featVid=document.querySelector('.featured-media video, .featured-media img');const featMedia=document.querySelector('.featured-media');const featFooterEl=document.querySelector('.featured-footer');const featTitre=document.querySelector('.featured-titre');const featChars=[];if(featTitre){const text=featTitre.textContent.trim();featTitre.setAttribute('aria-label',text);featTitre.innerHTML='';[...text].forEach((ch,i)=>{if(ch===' '){featTitre.appendChild(document.createTextNode('\u00a0'));return;}
const outer=document.createElement('span');outer.className='feat-char';const inner=document.createElement('span');inner.className='feat-char-inner';inner.textContent=ch;inner.style.setProperty('--cp','0');outer.appendChild(inner);featTitre.appendChild(outer);featChars.push({el:inner,i});});}
if(secFeat){fns.push(()=>{const p=easeOut3(scrollP(secFeat,0.92,0.2));const off=centerOffset(secFeat);set(featMedia,'--p-showreel',p.toFixed(4));if(featVid)set(featVid,'--p-showreel',p.toFixed(4));if(featVid)set(featVid,'--py-vid',(off*0.1).toFixed(2));set(featFooterEl,'--py-footer-info',(off*-0.08).toFixed(2));const N=featChars.length;const STAGGER=0.055;featChars.forEach(({el,i})=>{const cp=easeOut3(clamp((p-i*STAGGER)/(1-(N-1)*STAGGER*0.4),0,1));el.style.setProperty('--cp',cp.toFixed(4));});});}
const secRes=document.querySelector('.section-reseaux');const resLabel=document.querySelector('.section-reseaux .label-section');const resItems=secRes?.querySelectorAll('.reseaux-liste li')??[];if(secRes){fns.push(()=>{const p=scrollP(secRes,0.9,0.2);set(resLabel,'--p-reseaux',easeIO3(p).toFixed(4));resItems.forEach((li,i)=>{const rp=easeOut3(clamp((p-i*0.12)*4,0,1));li.style.setProperty('--rp',rp.toFixed(4));const lien=li.querySelector('.reseau-lien');if(lien)lien.style.setProperty('--rp',rp.toFixed(4));li.querySelectorAll('.reseau-nom, .reseau-fleche').forEach(c=>c.style.setProperty('--rp',rp.toFixed(4)));});});}
const secContact=document.querySelector('.section-contact');const titreCont=document.querySelector('.titre-contact');const emailEl=document.querySelector('.contact-inner .contact-email');const altEl=document.querySelector('.contact-alternance');const dispoEl=document.querySelector('.contact-dispo');if(titreCont&&secContact){const rawHTML=titreCont.innerHTML;const parts=rawHTML.split(/<br\s*\/?>/i);titreCont.innerHTML='';const lineInners=parts.map((html,i)=>{const mask=document.createElement('span');mask.className='ct-line-mask';const inner=document.createElement('span');inner.className='ct-line-inner';inner.innerHTML=html.trim();inner.style.setProperty('--cl-p','0');mask.appendChild(inner);titreCont.appendChild(mask);if(i<parts.length-1)titreCont.appendChild(document.createElement('br'));return inner;});fns.push(()=>{const p=scrollP(secContact,0.9,0.08);lineInners.forEach((el,i)=>{const STAGGER=0.2;const lp=easeOut3(clamp((p-i*STAGGER)/(1-(lineInners.length-1)*STAGGER*0.5),0,1));el.style.setProperty('--cl-p',lp.toFixed(4));});const pc=easeOut3(p);set(emailEl,'--p-contact',pc.toFixed(4));set(altEl,'--p-contact',pc.toFixed(4));set(dispoEl,'--p-contact',pc.toFixed(4));});}
const footer=document.querySelector('footer');if(footer)fns.push(()=>set(footer,'--p-footer',easeOut3(scrollP(footer,0.95,0.35)).toFixed(4)));document.querySelectorAll('.reseau-lien').forEach(el=>{let tx=0,ty=0,cx=0,cy=0,running=false;el.addEventListener('mousemove',e=>{const r=el.getBoundingClientRect();tx=(e.clientX-(r.left+r.width*0.5))*0.22;ty=(e.clientY-(r.top+r.height*0.5))*0.28;if(!running){running=true;go();}});el.addEventListener('mouseleave',()=>{tx=0;ty=0;});function go(){cx=lerp(cx,tx,0.1);cy=lerp(cy,ty,0.1);el.style.setProperty('--mx',cx.toFixed(2)+'px');el.style.setProperty('--my',cy.toFixed(2)+'px');if(Math.abs(cx-tx)>0.1||Math.abs(cy-ty)>0.1)requestAnimationFrame(go);else{running=false;el.style.setProperty('--mx','0px');el.style.setProperty('--my','0px');}}});setTimeout(()=>{const mail=document.querySelector('.contact-inner .contact-email');if(!mail)return;const bot=mail.querySelector('.ce-layer-bot');if(!bot)return;const orig=bot.textContent.trim();const pool='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz@._0123456789!#$%&*';let r=null;mail.addEventListener('mouseenter',()=>{if(r)cancelAnimationFrame(r);const t0=performance.now();const go=n=>{const prg=clamp((n-t0)/550,0,1);const rev=Math.floor(prg*orig.length);bot.textContent=[...orig].map((c,i)=>i<rev?c:pool[Math.floor(Math.random()*pool.length)]).join('');if(prg<1)r=requestAnimationFrame(go);else bot.textContent=orig;};r=requestAnimationFrame(go);});},400);requestAnimationFrame(tick);});(function initConnectStack(){const stack=document.querySelector('[data-cc-stack]');if(!stack)return;const cards=Array.from(stack.querySelectorAll('[data-cc-card]'));if(cards.length<2)return;const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;function getTopCard(){return stack.querySelector('.cc-card--top');}
function getBottomCard(){return cards.find(c=>!c.classList.contains('cc-card--top'));}
function syncAria(){cards.forEach(c=>{const isTop=c.classList.contains('cc-card--top');if(isTop)c.removeAttribute('aria-hidden');else c.setAttribute('aria-hidden','true');});}
function swapCards(){const top=getTopCard();const bottom=getBottomCard();if(!top||!bottom)return;top.classList.remove('cc-card--top');top.classList.add('is-swiping-out');bottom.classList.add('cc-card--top','is-incoming');syncAria();const cleanup=()=>{top.classList.remove('is-swiping-out');top.style.transform='';top.style.opacity='';bottom.classList.remove('is-incoming');};setTimeout(cleanup,reducedMotion?50:420);}
function handleToggleClick(e){e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();swapCards();}
const toggleBtns=stack.querySelectorAll('[data-cc-swipe]');toggleBtns.forEach(btn=>{btn.style.pointerEvents='auto';btn.addEventListener('click',handleToggleClick);});stack.addEventListener('click',(e)=>{const clickedCard=e.target.closest('.cc-card');if(!clickedCard)return;if(clickedCard.classList.contains('cc-card--top'))return;if(e.target.closest('a, input, textarea, button'))return;e.preventDefault();swapCards();});let dragState=null;function onPointerDown(e){const card=e.target.closest('.cc-card--top');if(!card)return;if(e.target.closest('input, textarea, a, button'))return;dragState={card,startX:e.clientX,startY:e.clientY,deltaX:0,deltaY:0,moved:false,pointerId:e.pointerId,};card.classList.add('is-dragging');card.setPointerCapture?.(e.pointerId);}
function onPointerMove(e){if(!dragState)return;dragState.deltaX=e.clientX-dragState.startX;dragState.deltaY=e.clientY-dragState.startY;if(Math.abs(dragState.deltaY)>Math.abs(dragState.deltaX)*1.5&&!dragState.moved){cancelDrag();return;}
if(Math.abs(dragState.deltaX)>4)dragState.moved=true;const rotation=Math.max(-18,Math.min(18,dragState.deltaX/12));const opacity=Math.max(0.4,1-Math.abs(dragState.deltaX)/600);dragState.card.style.transform=`translate(${dragState.deltaX}px, ${dragState.deltaY * 0.2}px) rotate(${rotation}deg)`;dragState.card.style.opacity=opacity;}
function onPointerUp(){if(!dragState)return;const{card,deltaX,moved}=dragState;const threshold=Math.max(80,card.offsetWidth*0.25);card.classList.remove('is-dragging');if(moved&&Math.abs(deltaX)>threshold){card.style.transform='';card.style.opacity='';swapCards();}else{card.style.transform='';card.style.opacity='';}
dragState=null;}
function cancelDrag(){if(!dragState)return;dragState.card.classList.remove('is-dragging');dragState.card.style.transform='';dragState.card.style.opacity='';dragState=null;}
if(!reducedMotion){stack.addEventListener('pointerdown',onPointerDown);window.addEventListener('pointermove',onPointerMove);window.addEventListener('pointerup',onPointerUp);window.addEventListener('pointercancel',cancelDrag);}
const form=stack.querySelector('[data-cc-form]');if(form){const feedback=form.querySelector('[data-cc-feedback]');const submitBtn=form.querySelector('button[type="submit"]');const labelSpan=submitBtn?.querySelector('.cc-cta-label');const tr=(key,fallback)=>{const lang=(window.langueActuelle)||document.documentElement.lang||'en';const dict=window.traductions||{};return dict[key]?.[lang]||fallback;};form.addEventListener('submit',async(e)=>{e.preventDefault();if(!form.checkValidity()){form.reportValidity();return;}
const labelDefault=tr('form.submit','Send message');const url=form.getAttribute('action');if(!url||url.includes('YOUR_FORMSPREE_ID')){if(feedback){feedback.textContent=tr('form.feedback.notconfigured','Form not configured yet (set Formspree ID).');feedback.classList.add('is-error');}
return;}
submitBtn.setAttribute('disabled','');if(labelSpan)labelSpan.textContent=tr('form.feedback.sending','Sending…');if(feedback){feedback.textContent='';feedback.classList.remove('is-error','is-success');}
try{const data=new FormData(form);const res=await fetch(url,{method:'POST',body:data,headers:{'Accept':'application/json'},});if(res.ok){if(feedback){feedback.textContent=tr('form.feedback.success','Message sent — thanks!');feedback.classList.add('is-success');}
form.reset();if(labelSpan)labelSpan.textContent=tr('form.feedback.sent','Sent ✓');setTimeout(()=>{submitBtn.removeAttribute('disabled');if(labelSpan)labelSpan.textContent=labelDefault;},3000);}else{throw new Error('Submit failed');}}catch(err){if(feedback){feedback.textContent=tr('form.feedback.error','Oops, something went wrong. Try again.');feedback.classList.add('is-error');}
submitBtn.removeAttribute('disabled');if(labelSpan)labelSpan.textContent=labelDefault;}});}})();