(function initConnectStack(){const stack=document.querySelector('[data-cc-stack]');if(!stack)return;const cards=Array.from(stack.querySelectorAll('[data-cc-card]'));if(cards.length<2)return;const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;function getTopCard(){return stack.querySelector('.cc-card--top');}
function getBottomCard(){return cards.find(c=>!c.classList.contains('cc-card--top'));}
function syncAria(){cards.forEach(c=>{const isTop=c.classList.contains('cc-card--top');if(isTop)c.removeAttribute('aria-hidden');else c.setAttribute('aria-hidden','true');});}
function swapCards(){const top=getTopCard();const bottom=getBottomCard();if(!top||!bottom)return;top.classList.remove('cc-card--top');top.classList.add('is-swiping-out');bottom.classList.add('cc-card--top','is-incoming');syncAria();const cleanup=()=>{top.classList.remove('is-swiping-out');top.style.transform='';top.style.opacity='';bottom.classList.remove('is-incoming');};setTimeout(cleanup,reducedMotion?50:420);}
function handleToggleClick(e){e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();swapCards();}
const toggleBtns=stack.querySelectorAll('[data-cc-swipe]');toggleBtns.forEach(btn=>{btn.style.pointerEvents='auto';btn.addEventListener('click',handleToggleClick);});stack.addEventListener('click',(e)=>{const clickedCard=e.target.closest('.cc-card');if(!clickedCard)return;if(clickedCard.classList.contains('cc-card--top'))return;if(e.target.closest('a, input, textarea, button'))return;e.preventDefault();swapCards();});let dragState=null;function onPointerDown(e){const card=e.target.closest('.cc-card--top');if(!card)return;if(e.target.closest('input, textarea, a, button'))return;dragState={card,startX:e.clientX,startY:e.clientY,deltaX:0,deltaY:0,moved:false,pointerId:e.pointerId,};card.classList.add('is-dragging');card.setPointerCapture?.(e.pointerId);}
function onPointerMove(e){if(!dragState)return;dragState.deltaX=e.clientX-dragState.startX;dragState.deltaY=e.clientY-dragState.startY;if(Math.abs(dragState.deltaY)>Math.abs(dragState.deltaX)*1.5&&!dragState.moved){cancelDrag();return;}
if(Math.abs(dragState.deltaX)>4)dragState.moved=true;const rotation=Math.max(-18,Math.min(18,dragState.deltaX/12));const opacity=Math.max(0.4,1-Math.abs(dragState.deltaX)/600);dragState.card.style.transform=`translate(${dragState.deltaX}px, ${dragState.deltaY * 0.2}px) rotate(${rotation}deg)`;dragState.card.style.opacity=opacity;}
function onPointerUp(){if(!dragState)return;const{card,deltaX,moved}=dragState;const threshold=Math.max(80,card.offsetWidth*0.25);card.classList.remove('is-dragging');if(moved&&Math.abs(deltaX)>threshold){card.style.transform='';card.style.opacity='';swapCards();}else{card.style.transform='';card.style.opacity='';}
dragState=null;}
function cancelDrag(){if(!dragState)return;dragState.card.classList.remove('is-dragging');dragState.card.style.transform='';dragState.card.style.opacity='';dragState=null;}
if(!reducedMotion){stack.addEventListener('pointerdown',onPointerDown);window.addEventListener('pointermove',onPointerMove);window.addEventListener('pointerup',onPointerUp);window.addEventListener('pointercancel',cancelDrag);}
const form=stack.querySelector('[data-cc-form]');if(form){const feedback=form.querySelector('[data-cc-feedback]');const submitBtn=form.querySelector('button[type="submit"]');const labelSpan=submitBtn?.querySelector('.cc-cta-label');const labelDefault=labelSpan?.textContent||'Send message';form.addEventListener('submit',async(e)=>{e.preventDefault();if(!form.checkValidity()){form.reportValidity();return;}
const url=form.getAttribute('action');if(!url||url.includes('YOUR_FORMSPREE_ID')){if(feedback){feedback.textContent='Form not configured yet (set Formspree ID).';feedback.classList.add('is-error');}
return;}
submitBtn.setAttribute('disabled','');if(labelSpan)labelSpan.textContent='Sending…';if(feedback){feedback.textContent='';feedback.classList.remove('is-error','is-success');}
try{const data=new FormData(form);const res=await fetch(url,{method:'POST',body:data,headers:{'Accept':'application/json'},});if(res.ok){if(feedback){feedback.textContent='Message sent — thanks!';feedback.classList.add('is-success');}
form.reset();if(labelSpan)labelSpan.textContent='Sent ✓';setTimeout(()=>{submitBtn.removeAttribute('disabled');if(labelSpan)labelSpan.textContent=labelDefault;},3000);}else{throw new Error('Submit failed');}}catch(err){if(feedback){feedback.textContent='Oops, something went wrong. Try again.';feedback.classList.add('is-error');}
submitBtn.removeAttribute('disabled');if(labelSpan)labelSpan.textContent=labelDefault;}});}})();