document.addEventListener('DOMContentLoaded',()=>{const liste=document.getElementById('projets-liste');const btnListe=document.getElementById('btn-vue-liste');const btnGrille=document.getElementById('btn-vue-grille');if(!liste||!btnListe||!btnGrille)return;if(typeof PROJETS!=='undefined'&&PROJETS.length>0){liste.innerHTML='';PROJETS.forEach((projet,index)=>{const numero=String(index+1).padStart(2,'0');let coverHtml;if(projet.cover){if(projet.video){coverHtml=`<video autoplay muted loop playsinline preload="metadata" aria-hidden="true"><source src="${projet.cover}"></video>`;}else{coverHtml=`<img src="${projet.cover}" alt="${projet.nom}" loading="lazy">`;}}else{coverHtml=`<div class="projet-cover-placeholder"></div>`;}
const article=document.createElement('article');article.className='projet-item apparaitre';article.dataset.industrie=projet.industrie||'all';article.dataset.type=Array.isArray(projet.type)?projet.type.join(' '):'';article.dataset.index=index;const metaKey=projet.slug?`projets.meta.${projet.slug}`:'';const metaAttr=metaKey?` data-i18n="${metaKey}"`:'';const metaText=metaKey&&window.traductions?.[metaKey]?.[window.langueActuelle||'en']||projet.meta;article.innerHTML=`
        <a href="${projet.href}" class="projet-cover-lien" aria-hidden="true" tabindex="-1">
          <div class="projet-cover" aria-hidden="true">${coverHtml}</div>
        </a>
        <a href="${projet.href}" class="projet-lien" data-curseur>
          <div class="projet-info">
            <span class="projet-numero">${numero}</span>
            <h2 class="projet-nom">${projet.nom}</h2>
            <p class="projet-meta"${metaAttr}>${metaText}</p>
          </div>
          <span class="projet-item-arrow" aria-hidden="true">↗</span>
        </a>`;liste.appendChild(article);});if(window.observateurApparition){liste.querySelectorAll('.apparaitre').forEach(el=>{window.observateurApparition.observe(el);});}}
function injecterSplitNav(){const ancien=liste.querySelector('.split-nav');if(ancien)ancien.remove();const ancienMain=liste.querySelector('.split-main');if(ancienMain){while(ancienMain.firstChild){liste.appendChild(ancienMain.firstChild);}
ancienMain.remove();}
const articles=Array.from(liste.querySelectorAll('.projet-item'));if(articles.length===0)return;const nav=document.createElement('nav');nav.className='split-nav';nav.setAttribute('aria-label',(window.langueActuelle==='fr')?'Index des projets':'Project index');const track=document.createElement('div');track.className='split-nav-track';articles.forEach((article,i)=>{const nomEl=article.querySelector('.projet-nom');const numEl=article.querySelector('.projet-numero');const href=article.querySelector('.projet-lien')?.getAttribute('href')||'#';const nom=nomEl?nomEl.textContent.trim():`Projet ${i + 1}`;const num=numEl?numEl.textContent.trim():String(i+1).padStart(2,'0');const item=document.createElement('a');item.className='split-nav-item';item.href=href;item.dataset.idx=i;item.innerHTML=`
        <span class="split-nav-titre">${nom}</span>
        <span class="split-nav-num">${num}</span>`;item.addEventListener('click',(e)=>{e.preventDefault();article.scrollIntoView({behavior:'smooth',block:'center'});});track.appendChild(item);});nav.appendChild(track);nav.style.maxWidth='0';nav.style.paddingRight='0';nav.style.opacity='0';nav.style.overflow='hidden';const main=document.createElement('div');main.className='split-main';articles.forEach(a=>main.appendChild(a));liste.appendChild(nav);liste.appendChild(main);return{nav,track};}
let observeur=null;let scrollHandler=null;function initialiserObserveur(){if(observeur){observeur.disconnect();observeur=null;}
if(scrollHandler){window.removeEventListener('scroll',scrollHandler);scrollHandler=null;}
const navItems=document.querySelectorAll('.split-nav-item');const track=document.querySelector('.split-nav-track');const nav=document.querySelector('.split-nav');if(!navItems.length||!track||!nav)return;const articles=document.querySelectorAll('.projet-item');if(!articles.length)return;let indexActif=-1;let transitionEnabled=false;const main=document.querySelector('.split-main');requestAnimationFrame(()=>{void nav.offsetWidth;transitionEnabled=true;if(main)main.style.transition='margin-left 1s cubic-bezier(0.65, 0, 0.35, 1)';});function mettreAJourVisibilite(){const listeEl=document.querySelector('.projets-grille.vue-liste');if(!listeEl)return;const sectionAbsTop=listeEl.getBoundingClientRect().top+window.scrollY;const scrolledIn=window.scrollY-sectionAbsTop;const visible=scrolledIn>200;if(transitionEnabled){nav.style.transition=visible?'max-width 1s cubic-bezier(0.65, 0, 0.35, 1), padding-right 1s cubic-bezier(0.65, 0, 0.35, 1), opacity 0.6s ease 0.4s':'max-width 1s cubic-bezier(0.65, 0, 0.35, 1), padding-right 1s cubic-bezier(0.65, 0, 0.35, 1), opacity 0.35s ease';}
nav.style.opacity=visible?'1':'0';nav.style.maxWidth=visible?'clamp(320px, 32vw, 460px)':'0';nav.style.paddingRight=visible?'':'0';nav.style.overflow=visible?'':'hidden';if(main)main.style.marginLeft=visible?'2rem':'0';listeEl.classList.toggle('nav-visible',visible);}
function activerIndex(idx){if(idx===indexActif)return;indexActif=idx;navItems.forEach(item=>{if(item.classList.contains('actif')){item.style.transition='opacity 0.3s ease';item.classList.remove('actif');}else{item.style.transition='none';item.classList.remove('actif');}});setTimeout(()=>{navItems.forEach(item=>{item.style.transition='';});if(navItems[idx])navItems[idx].classList.add('actif');},300);}
function mettreAJourActif(){const centre=window.innerHeight/2;let meilleurIdx=0;let distMin=Infinity;articles.forEach((article,i)=>{const r=article.getBoundingClientRect();const dist=Math.abs(r.top+r.height/2-centre);if(dist<distMin){distMin=dist;meilleurIdx=i;}});activerIndex(meilleurIdx);}
scrollHandler=()=>{mettreAJourVisibilite();mettreAJourActif();};window.addEventListener('scroll',scrollHandler,{passive:true});mettreAJourVisibilite();mettreAJourActif();}
const vueSauvee=localStorage.getItem('vue-projets')||'liste';_changerVue(vueSauvee);btnListe.addEventListener('click',()=>appliquerVue('liste'));btnGrille.addEventListener('click',()=>appliquerVue('grille'));function appliquerVue(vue){const vueActuelle=liste.classList.contains('vue-grille')?'grille':'liste';if(vue===vueActuelle)return;liste.style.opacity='0';liste.style.transform='translateY(10px)';setTimeout(()=>{_changerVue(vue);void liste.offsetHeight;liste.style.opacity='1';liste.style.transform='translateY(0)';},220);}
function _changerVue(vue){if(vue==='grille'){_demantelerSplit();liste.classList.replace('vue-liste','vue-grille')||(liste.classList.remove('vue-liste'),liste.classList.add('vue-grille'));btnGrille.classList.add('actif');btnListe.classList.remove('actif');btnGrille.setAttribute('aria-pressed','true');btnListe.setAttribute('aria-pressed','false');}else{liste.classList.replace('vue-grille','vue-liste')||(liste.classList.remove('vue-grille'),liste.classList.add('vue-liste'));btnListe.classList.add('actif');btnGrille.classList.remove('actif');btnListe.setAttribute('aria-pressed','true');btnGrille.setAttribute('aria-pressed','false');_monterSplit();}
localStorage.setItem('vue-projets',vue);}
function _monterSplit(){if(window.innerWidth<=900)return;injecterSplitNav();requestAnimationFrame(()=>{requestAnimationFrame(()=>{initialiserObserveur();});});}
function _demantelerSplit(){if(observeur){observeur.disconnect();observeur=null;}
if(scrollHandler){window.removeEventListener('scroll',scrollHandler);scrollHandler=null;}
const nav=liste.querySelector('.split-nav');const main=liste.querySelector('.split-main');if(main){while(main.firstChild){liste.appendChild(main.firstChild);}
main.remove();}
if(nav)nav.remove();}
let derniereVue='';window.addEventListener('resize',()=>{const vueActuelle=liste.classList.contains('vue-grille')?'grille':'liste';if(vueActuelle!=='liste')return;const estDesktop=window.innerWidth>900;const aSplitNav=!!liste.querySelector('.split-nav');if(estDesktop&&!aSplitNav){_monterSplit();}else if(!estDesktop&&aSplitNav){_demantelerSplit();}});const dropdownIndustrie=document.getElementById('filtre-industrie');const dropdownType=document.getElementById('filtre-type');if(dropdownIndustrie&&dropdownType){let filtreIndustrie='all';let filtreType='all';function appliquerFiltres(){const articles=liste.querySelectorAll('.projet-item');let visibleIndex=0;articles.forEach(article=>{const industrie=article.dataset.industrie||'';const types=(article.dataset.type||'').split(' ');const visible=(filtreIndustrie==='all'||industrie===filtreIndustrie)&&(filtreType==='all'||types.includes(filtreType));if(visible){article.style.display='';const delay=visibleIndex*0.05;article.style.transition=`opacity 0.5s var(--ease-out) ${delay}s, transform 0.5s var(--ease-out) ${delay}s`;article.style.opacity='0';article.style.transform='translateY(16px)';requestAnimationFrame(()=>{requestAnimationFrame(()=>{article.style.opacity='1';article.style.transform='translateY(0)';});});visibleIndex++;}else{article.style.opacity='0';article.style.transform='translateY(-8px)';setTimeout(()=>{article.style.display='none';},300);}});const navItems=document.querySelectorAll('.split-nav-item');navItems.forEach((navItem,i)=>{const article=articles[i];if(!article)return;const industrie=article.dataset.industrie||'';const types=(article.dataset.type||'').split(' ');const visible=(filtreIndustrie==='all'||industrie===filtreIndustrie)&&(filtreType==='all'||types.includes(filtreType));navItem.style.opacity=visible?'':'0.05';navItem.style.pointerEvents=visible?'':'none';});}
function fermerDropdowns(){document.querySelectorAll('.filtre-dropdown.ouvert').forEach(d=>{d.classList.remove('ouvert');d.querySelector('.filtre-dropdown-btn').setAttribute('aria-expanded','false');});}
function initDropdown(dropdown,getVal,setFiltre,defaultLabel){const btn=dropdown.querySelector('.filtre-dropdown-btn');const valEl=dropdown.querySelector('.filtre-dropdown-val');const items=dropdown.querySelectorAll('.filtre-dropdown-item');btn.addEventListener('click',(e)=>{e.stopPropagation();const isOpen=dropdown.classList.contains('ouvert');fermerDropdowns();if(!isOpen){dropdown.classList.add('ouvert');btn.setAttribute('aria-expanded','true');}});items.forEach(item=>{item.addEventListener('click',()=>{const val=getVal(item);setFiltre(val);items.forEach(i=>{i.classList.toggle('actif',i===item);i.setAttribute('aria-selected',i===item?'true':'false');});valEl.textContent=val==='all'?defaultLabel:item.textContent;btn.classList.toggle('actif',val!=='all');fermerDropdowns();appliquerFiltres();});});}
const tr=(key,fallback)=>{const lang=(window.langueActuelle)||document.documentElement.lang||'en';return window.traductions?.[key]?.[lang]||fallback;};initDropdown(dropdownIndustrie,item=>item.dataset.filtreIndustrie,val=>{filtreIndustrie=val;},tr('filtres.industrie','By Industry'));initDropdown(dropdownType,item=>item.dataset.filtreType,val=>{filtreType=val;},tr('filtres.type','By Type'));document.addEventListener('click',fermerDropdowns);const dotsBtn=document.querySelector('.filtre-dots-btn');if(dotsBtn){const backdrop=document.createElement('div');backdrop.className='filtre-popup-backdrop';document.body.appendChild(backdrop);const popup=document.createElement('div');popup.className='filtre-popup';const lblIndustrie=document.createElement('p');lblIndustrie.className='filtre-popup-label';lblIndustrie.textContent=tr('filtres.industrie','By Industry');lblIndustrie.dataset.i18n='filtres.industrie';popup.appendChild(lblIndustrie);dropdownIndustrie.querySelectorAll('.filtre-dropdown-item').forEach(item=>{const clone=item.cloneNode(true);clone.dataset.popupGroup='industrie';popup.appendChild(clone);});const lblType=document.createElement('p');lblType.className='filtre-popup-label';lblType.style.marginTop='1.2rem';lblType.textContent=tr('filtres.type','By Type');lblType.dataset.i18n='filtres.type';popup.appendChild(lblType);dropdownType.querySelectorAll('.filtre-dropdown-item').forEach(item=>{const clone=item.cloneNode(true);clone.dataset.popupGroup='type';popup.appendChild(clone);});document.body.appendChild(popup);function syncPopupActif(){popup.querySelectorAll('[data-popup-group="industrie"]').forEach(b=>{b.classList.toggle('actif',b.dataset.filtreIndustrie===filtreIndustrie);});popup.querySelectorAll('[data-popup-group="type"]').forEach(b=>{b.classList.toggle('actif',b.dataset.filtreType===filtreType);});}
function ouvrirPopup(){popup.style.display='flex';void popup.offsetHeight;popup.classList.add('visible');backdrop.classList.add('visible');dotsBtn.classList.add('actif');syncPopupActif();}
function fermerPopup(){popup.classList.remove('visible');backdrop.classList.remove('visible');dotsBtn.classList.remove('actif');setTimeout(()=>{popup.style.display='none';},250);}
dotsBtn.addEventListener('click',(e)=>{e.stopPropagation();popup.classList.contains('visible')?fermerPopup():ouvrirPopup();});backdrop.addEventListener('click',fermerPopup);popup.addEventListener('click',(e)=>{const item=e.target.closest('.filtre-dropdown-item');if(!item)return;const group=item.dataset.popupGroup;if(group==='industrie'){filtreIndustrie=item.dataset.filtreIndustrie;dropdownIndustrie.querySelectorAll('.filtre-dropdown-item').forEach(i=>{i.classList.toggle('actif',i.dataset.filtreIndustrie===filtreIndustrie);});const valEl=dropdownIndustrie.querySelector('.filtre-dropdown-val');const btn=dropdownIndustrie.querySelector('.filtre-dropdown-btn');valEl.textContent=filtreIndustrie==='all'?tr('filtres.industrie','By Industry'):item.textContent;btn.classList.toggle('actif',filtreIndustrie!=='all');}else{filtreType=item.dataset.filtreType;dropdownType.querySelectorAll('.filtre-dropdown-item').forEach(i=>{i.classList.toggle('actif',i.dataset.filtreType===filtreType);});const valEl=dropdownType.querySelector('.filtre-dropdown-val');const btn=dropdownType.querySelector('.filtre-dropdown-btn');valEl.textContent=filtreType==='all'?tr('filtres.type','By Type'):item.textContent;btn.classList.toggle('actif',filtreType!=='all');}
appliquerFiltres();fermerPopup();});}}});