(function(){'use strict';var USER_HAS_INTERACTED=false;function markInteracted(){USER_HAS_INTERACTED=true;}
document.addEventListener('click',markInteracted,{once:true,capture:true});document.addEventListener('keydown',markInteracted,{once:true,capture:true});document.addEventListener('touchstart',markInteracted,{once:true,capture:true});function killLenis(){document.documentElement.classList.add('no-lenis');if(window.__lenis){try{window.__lenis.stop();if(typeof window.__lenis.destroy==='function'){window.__lenis.destroy();}}catch(_){}
window.__lenis=null;}
document.documentElement.classList.remove('lenis','lenis-smooth','lenis-scrolling','lenis-stopped');}
function splitToLetters(el,baseDelay){if(!el||el.dataset.split==='1')return;el.dataset.split='1';var lignes=[];var courante='';el.childNodes.forEach(function(node){if(node.nodeType===Node.TEXT_NODE){courante+=node.textContent;}else if(node.nodeName==='BR'){lignes.push(courante);courante='';}else{courante+=node.textContent||'';}});lignes.push(courante);el.innerHTML='';var totalIdx=0;lignes.forEach(function(ligne,ligneIdx){if(ligneIdx>0)el.appendChild(document.createElement('br'));var wrap=document.createElement('span');wrap.style.display='inline-block';wrap.style.overflow='hidden';wrap.style.lineHeight='inherit';wrap.style.paddingBottom='0.08em';wrap.style.verticalAlign='top';Array.from(ligne).forEach(function(ch){var sp=document.createElement('span');sp.className='ltr';sp.textContent=(ch===' ')?'\u00A0':ch;sp.style.setProperty('--ad',((baseDelay||0.30)+totalIdx*0.045)+'s');wrap.appendChild(sp);totalIdx++;});el.appendChild(wrap);});}
function splitToLines(el,lineClassName){if(!el||el.dataset.split==='1')return;el.dataset.split='1';var lignes=[];var html='';Array.from(el.childNodes).forEach(function(node){if(node.nodeName==='BR'){lignes.push(html);html='';}
else if(node.nodeType===Node.TEXT_NODE)html+=node.textContent;else html+=node.outerHTML;});if(html)lignes.push(html);el.innerHTML='';lignes.forEach(function(l){var wrap=document.createElement('span');wrap.className=lineClassName;var inner=document.createElement('span');inner.innerHTML=l;wrap.appendChild(inner);el.appendChild(wrap);});}
function initHeroAnimation(root){var hero=root.querySelector('.proj-vitrine--hero');if(!hero)return;var titre=hero.querySelector('.proj-hero-titre');if(titre)splitToLetters(titre,0.30);requestAnimationFrame(function(){requestAnimationFrame(function(){hero.classList.add('proj-hero-ready');});});}
function initScrollReveal(root){if(!('IntersectionObserver'in window)){root.querySelectorAll('.proj-vitrine--intro, .proj-vitrine--slide').forEach(function(v){v.classList.add('is-revealed');});return;}
var isInjected=root!==document&&root.classList.contains('proj-page-shell--injected');var io=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting&&entry.intersectionRatio>0.25){entry.target.classList.add('is-revealed');io.unobserve(entry.target);}});},{threshold:[0,0.25,0.5],rootMargin:'0px 0px -10% 0px',root:isInjected?root:null,});root.querySelectorAll('.proj-vitrine--intro, .proj-vitrine--slide').forEach(function(v){io.observe(v);});}
function initSlideVideos(root){var medias=root.querySelectorAll('.proj-slide-media.is-video');if(!medias.length)return;medias.forEach(function(container){if(container.dataset.videoBound==='1')return;container.dataset.videoBound='1';var video=container.querySelector('video');if(!video)return;video.loop=false;video.autoplay=false;video.controls=false;video.playsInline=true;video.muted=true;video.removeAttribute('autoplay');video.removeAttribute('loop');try{video.preload=(window.__lowPerf?'metadata':'auto');if(video.readyState<1){video.addEventListener('loadedmetadata',function(){try{video.currentTime=0.01;}catch(_){}},{once:true});}else{try{video.currentTime=0.01;}catch(_){}}}catch(_){}
container.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();markInteracted();toggleVideo(container,video);});video.addEventListener('ended',function(){container.classList.remove('is-playing');});});}
function playVideoWithSound(container,video){var canTrySound=USER_HAS_INTERACTED;if(canTrySound){video.muted=false;}else{video.muted=true;}
var p=video.play();if(p&&typeof p.then==='function'){p.then(function(){container.classList.add('is-playing');}).catch(function(){video.muted=true;video.play().then(function(){container.classList.add('is-playing');}).catch(function(){container.classList.remove('is-playing');});});}else{container.classList.add('is-playing');}}
function pauseVideoKeepTime(container,video){if(!video.paused){try{video.pause();}catch(_){}}
video.muted=true;container.classList.remove('is-playing');}
function toggleVideo(container,video){if(!video.paused){pauseVideoKeepTime(container,video);}else{playVideoWithSound(container,video);}}
function initVideoSnapBehavior(root){var isInjected=root!==document&&root.classList.contains('proj-page-shell--injected');var emitter=isInjected?root:document;function syncWithActive(activeVitrine){root.querySelectorAll('.proj-slide-media.is-video').forEach(function(container){var video=container.querySelector('video');if(!video)return;var inActive=activeVitrine&&activeVitrine.contains(container);if(inActive){playVideoWithSound(container,video);}else{pauseVideoKeepTime(container,video);}});}
emitter.addEventListener('snapvitrine:change',function(e){var v=e.detail&&e.detail.vitrine;syncWithActive(v);});requestAnimationFrame(function(){var allVitrines=root.querySelectorAll(':scope > .proj-vitrine, .proj-page-shell > .proj-vitrine');var activeVitrine=null;var bestDist=Infinity;var scrollerTop=isInjected?root.scrollTop:(window.scrollY||0);allVitrines.forEach(function(v){var rect=v.getBoundingClientRect();var ref=isInjected?root.getBoundingClientRect():{top:0};var top=rect.top-ref.top+scrollerTop;var dist=Math.abs(top-scrollerTop);if(dist<bestDist){bestDist=dist;activeVitrine=v;}});if(activeVitrine)syncWithActive(activeVitrine);});}
function initHeroVideo(root){root.querySelectorAll('.proj-vitrine--hero video').forEach(function(v){v.muted=true;v.loop=true;v.playsInline=true;try{v.play();}catch(_){}});}
function initScrollHint(root,opts){var hero=root.querySelector('.proj-vitrine--hero');var hint=hero&&hero.querySelector('.proj-scroll-hint');if(!hero||!hint)return;var isInjected=root!==document&&root.classList.contains('proj-page-shell--injected');var scroller=isInjected?root:window;function getY(){return isInjected?root.scrollTop:(window.scrollY||0);}
function onScroll(){hint.classList.toggle('is-hidden',getY()>40);}
scroller.addEventListener('scroll',onScroll,{passive:true});onScroll();hint.addEventListener('click',function(){var next=hero.nextElementSibling;if(next&&next.scrollIntoView)next.scrollIntoView({behavior:'smooth'});});}
function pad2(n){return n<10?'0'+n:''+n;}
function cleanCaption(alt,nom){if(!alt)return'';var a=alt.trim();var nomLower=(nom||'').toLowerCase();var sepIdx=-1;['—',' - '].forEach(function(sep){if(sepIdx!==-1)return;var idx=a.indexOf(sep);if(idx!==-1)sepIdx=idx+(sep==='—'?1:sep.length);});if(sepIdx!==-1){var prefix=a.slice(0,sepIdx).replace(/[—-]/g,'').trim().toLowerCase();if(prefix===nomLower){return a.slice(sepIdx).replace(/^[—-]\s*/,'').trim();}}
return a;}
function deriveCaption(vitrine,nom){if(vitrine.querySelector('.proj-grid-media'))return'Suite d\u2019ic\u00f4nes';var duoImgs=vitrine.querySelectorAll('.proj-duo-item img');if(duoImgs.length){var parts=Array.prototype.map.call(duoImgs,function(img){return cleanCaption(img.getAttribute('alt'),nom);}).filter(Boolean);return parts.join(' \u2014 ');}
var media=vitrine.querySelector('img, video');if(!media)return'';return cleanCaption(media.getAttribute('alt'),nom);}
function initSlideTags(root,nom){var slides=Array.prototype.slice.call(root.querySelectorAll('.proj-vitrine--slide'));if(!slides.length)return;slides.forEach(function(v){if(v.querySelector('.proj-slide-title'))return;var caption=deriveCaption(v,nom);if(!caption)return;var tag=document.createElement('div');tag.className='proj-slide-title';tag.setAttribute('aria-hidden','true');var cap=document.createElement('span');cap.className='proj-slide-title-text';cap.textContent=caption;tag.appendChild(cap);v.appendChild(tag);});}
function initProjNav(root,opts){var vitrines=Array.prototype.slice.call(root.querySelectorAll(':scope > .proj-vitrine, .proj-page-shell > .proj-vitrine'));if(vitrines.length<3)return;var shell=(opts&&opts.spa)?root:document.querySelector('.proj-page-shell');if(!shell||shell.querySelector('.proj-rail'))return;var slideVitrines=vitrines.filter(function(v){return v.classList.contains('proj-vitrine--slide');});var rail=document.createElement('div');rail.className='proj-rail';rail.setAttribute('aria-hidden','true');vitrines.forEach(function(v){var dot=document.createElement('button');dot.type='button';dot.className='proj-rail-dot';dot.tabIndex=-1;dot.addEventListener('click',function(){v.scrollIntoView({behavior:'smooth'});});rail.appendChild(dot);});shell.appendChild(rail);var dots=rail.querySelectorAll('.proj-rail-dot');var counter=null,counterCur=null;if(slideVitrines.length){counter=document.createElement('div');counter.className='proj-slide-counter';counter.setAttribute('aria-hidden','true');counterCur=document.createElement('span');counterCur.className='proj-slide-counter-cur';var sep=document.createElement('span');sep.className='proj-slide-counter-sep';sep.textContent='/';var tot=document.createElement('span');tot.textContent=pad2(slideVitrines.length);counter.appendChild(counterCur);counter.appendChild(sep);counter.appendChild(tot);shell.appendChild(counter);}
var isInjected=root!==document&&root.classList.contains('proj-page-shell--injected');if(!('IntersectionObserver'in window))return;var io=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(!(entry.isIntersecting&&entry.intersectionRatio>0.5))return;var idx=vitrines.indexOf(entry.target);if(idx===-1)return;dots.forEach(function(d,i){d.classList.toggle('is-active',i===idx);});if(counter){var slideIdx=slideVitrines.indexOf(entry.target);if(slideIdx!==-1){counterCur.textContent=pad2(slideIdx+1);counter.classList.add('visible');}else{counter.classList.remove('visible');}}});},{threshold:[0.5],root:isInjected?root:null});vitrines.forEach(function(v){io.observe(v);});}
function initTilt(root){if(!window.matchMedia||!window.matchMedia('(pointer:fine)').matches)return;var targets=root.querySelectorAll('.proj-slide-media img, .proj-slide-media video, .proj-duo-item img, .proj-grid-item img');targets.forEach(function(el){if(el.dataset.tiltBound==='1')return;el.dataset.tiltBound='1';var parent=el.closest('.proj-slide-media, .proj-duo-item, .proj-grid-item');if(!parent)return;var raf=null;function onMove(e){var rect=parent.getBoundingClientRect();if(!rect.width||!rect.height)return;var px=(e.clientX-rect.left)/rect.width-0.5;var py=(e.clientY-rect.top)/rect.height-0.5;if(raf)return;raf=requestAnimationFrame(function(){raf=null;el.style.setProperty('--tilt-y',(px*7).toFixed(2)+'deg');el.style.setProperty('--tilt-x',(py*-7).toFixed(2)+'deg');el.style.setProperty('--tilt-s','1.035');});}
function onLeave(){el.style.setProperty('--tilt-x','0deg');el.style.setProperty('--tilt-y','0deg');el.style.setProperty('--tilt-s','1');}
parent.addEventListener('mousemove',onMove);parent.addEventListener('mouseleave',onLeave);});}
function initRetourFleche(root,opts){var fleche=(opts&&opts.spa)?root.querySelector('.retour-fleche'):document.querySelector('.retour-fleche');if(!fleche)return;fleche.classList.add('visible');}
function initScrollToBack(root,opts){var vitrines=root.querySelectorAll(':scope > .proj-vitrine, .proj-page-shell > .proj-vitrine');var lastVitrine=null;vitrines.forEach(function(v){lastVitrine=v;});if(!lastVitrine)return;var isInjected=root!==document&&root.classList.contains('proj-page-shell--injected');var scroller=isInjected?root:document.documentElement;var endVisible=false;var io=new IntersectionObserver(function(entries){entries.forEach(function(e){endVisible=e.isIntersecting&&e.intersectionRatio>0.6;});},{threshold:[0,0.6,1],root:isInjected?scroller:null,});io.observe(lastVitrine);var wheelAccum=0;var lastWheelTime=0;var triggered=false;var TRIGGER_THRESHOLD=220;var WHEEL_RESET_MS=700;function isAtBottom(){if(isInjected){return scroller.scrollTop+scroller.clientHeight>=scroller.scrollHeight-4;}
var max=document.documentElement.scrollHeight-window.innerHeight;return(window.scrollY||0)>=max-4;}
function triggerBack(){if(triggered)return;triggered=true;if(opts&&opts.spa&&typeof window.__projetZoomBack==='function'){if(window.__projetZoomBack())return;}
var originUrl='/work';try{var raw=sessionStorage.getItem('wol-zoom-return');if(raw){var data=JSON.parse(raw);if(data&&data.originUrl)originUrl=data.originUrl;}}catch(_){}
var ease='cubic-bezier(0.25, 1, 0.5, 1)';document.body.style.transition='opacity 0.5s '+ease;document.body.style.opacity='0';setTimeout(function(){window.location.href=originUrl;},510);}
function onWheel(e){if(!endVisible||!isAtBottom()){wheelAccum=0;return;}
var now=performance.now();if(now-lastWheelTime>WHEEL_RESET_MS)wheelAccum=0;lastWheelTime=now;var dy=e.deltaMode===1?e.deltaY*40:e.deltaMode===2?e.deltaY*window.innerHeight:e.deltaY;if(dy>0){wheelAccum+=dy;e.preventDefault();if(wheelAccum>=TRIGGER_THRESHOLD)triggerBack();}else{wheelAccum=0;}}
var touchStartY=null;var touchAccum=0;var TOUCH_THRESHOLD=120;function onTouchStart(e){if(!endVisible||!isAtBottom()){touchStartY=null;return;}
touchStartY=e.touches[0].clientY;touchAccum=0;}
function onTouchMove(e){if(touchStartY==null)return;if(!endVisible||!isAtBottom()){touchStartY=null;return;}
var dy=touchStartY-e.touches[0].clientY;if(dy>0){touchAccum=dy;if(touchAccum>=TOUCH_THRESHOLD)triggerBack();}}
function onTouchEnd(){touchStartY=null;touchAccum=0;}
var target=isInjected?scroller:window;target.addEventListener('wheel',onWheel,{passive:false});target.addEventListener('touchstart',onTouchStart,{passive:true});target.addEventListener('touchmove',onTouchMove,{passive:true});target.addEventListener('touchend',onTouchEnd,{passive:true});}
function initProgressBar(root,opts){if(!opts||!opts.spa)return;var isInjected=root!==document&&root.classList.contains('proj-page-shell--injected');if(!isInjected)return;var barre=document.getElementById('scroll-progress');if(!barre)return;var rafId=null;function update(){rafId=null;var scrollTop=root.scrollTop;var docHeight=root.scrollHeight-root.clientHeight;var progression=docHeight>0?scrollTop/docHeight:0;barre.style.setProperty('--progress',progression);}
function onScroll(){if(!rafId)rafId=requestAnimationFrame(update);}
root.addEventListener('scroll',onScroll,{passive:true});update();root._progressHandler=onScroll;}
function initProjetSingle(root,opts){root=root||document;opts=opts||{};initHeroAnimation(root);initScrollReveal(root);initSlideVideos(root);initVideoSnapBehavior(root);initHeroVideo(root);initRetourFleche(root,opts);initScrollHint(root,opts);initProgressBar(root,opts);var heroTitreEl=root.querySelector('.proj-hero-titre');var nomProjet=heroTitreEl?heroTitreEl.textContent.replace(/\u00A0/g,' ').trim():'';initSlideTags(root,nomProjet);initProjNav(root,opts);initTilt(root);function bindScrollToBack(){initScrollToBack(root,opts);}
if(typeof window.initSnapVitrines==='function'){if(opts.spa){requestAnimationFrame(function(){requestAnimationFrame(function(){window.initSnapVitrines(root);bindScrollToBack();});});}else{window.initSnapVitrines(root);bindScrollToBack();}}else{bindScrollToBack();}}
window.initProjetSingle=initProjetSingle;function isDirectLoad(){return document.body.classList.contains('page-projet-single');}
function boot(){if(!isDirectLoad())return;killLenis();var tries=0;var interval=setInterval(function(){killLenis();if(++tries>30)clearInterval(interval);},100);initProjetSingle(document,{spa:false});}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',boot);}else{boot();}})();